@namespace
class SpriteKind:
    w = SpriteKind.create()
    key = SpriteKind.create()
    box = SpriteKind.create()
    cookie = SpriteKind.create()
    Gateway = SpriteKind.create()
    map2 = SpriteKind.create()
    IN = SpriteKind.create()
    VILl1 = SpriteKind.create()
    gateway2 = SpriteKind.create()
    KEYD = SpriteKind.create()
    VIL2 = SpriteKind.create()
    VIL3 = SpriteKind.create()
    gate3 = SpriteKind.create()
    Ghost = SpriteKind.create()
    Boss = SpriteKind.create()
    Spear = SpriteKind.create()
def _3_sprite_LV2():
    global _3s
    sprites.destroy_all_sprites_of_kind(SpriteKind.player)
    sprites.destroy_all_sprites_of_kind(SpriteKind.projectile)
    sprites.destroy_all_sprites_of_kind(SpriteKind.VIL2)
    sprites.destroy_all_sprites_of_kind(SpriteKind.VIL3)
    sprites.destroy_all_sprites_of_kind(SpriteKind.VILl1)
    sprites.destroy_all_sprites_of_kind(SpriteKind.enemy)
    sprites.destroy_all_sprites_of_kind(SpriteKind.map2)
    sprites.destroy_all_sprites_of_kind(SpriteKind.text)
    scene.set_tile_map(assets.image("""
        fright
        """))
    scene.set_tile(2,
        img("""
            e d e e e e e e e d e e e e e e
            e d e e e e e e e d e e e e e e
            e d e e e e e e e d e e e e e e
            d d d d d d d d d d d d d d d d
            e e e e e d e e e e e e e d e e
            e e e e e d e e e e e e e d e e
            e e e e e d e e e e e e e d e e
            d d d d d d d d d d d d d d d d
            e d e e e e e e e d e e e e e e
            e d e e e e e e e d e e e e e e
            e d e e e e e e e d e e e e e e
            d d d d d d d d d d d d d d d d
            e e e e e d e e e e e e e d e e
            e e e e e d e e e e e e e d e e
            e e e e e d e e e e e e e d e e
            d d d d d d d d d d d d d d d d
            """),
        True)
    scene.set_tile(5, assets.image("""
        船
        """), False)
    scene.set_tile(7,
        img("""
            . . . . . . . . . . . . . . . .
            . . . . . . c c c c 6 . . . . .
            . . . . c c 6 7 7 5 5 6 6 . . .
            . . c c 6 6 6 6 7 5 5 7 c c . .
            . c 6 6 6 7 7 7 7 7 7 5 6 c c .
            . c 6 6 7 7 7 5 7 6 7 7 7 6 c c
            c 6 6 7 7 6 7 7 7 6 7 7 6 6 6 c
            c c 6 6 6 7 6 7 6 6 6 6 5 7 6 c
            c c c c 6 7 7 6 7 7 7 6 7 6 6 c
            . c c 6 6 6 6 c 6 6 6 6 6 c c c
            . c c 6 6 c 6 6 c 6 c 6 6 c c .
            . . c c f f 6 6 c f f c c f . .
            . . . . c f c c c f c f f . . .
            . . . . . 4 f f f c . e . . . .
            . . . . . . e e e . . 4 . . . .
            . . . . . . . e e . e . . . . .
            """),
        True)
    scene.set_background_image(assets.image("""
        Home pages
        """))
    _3s = sprites.create(assets.image("""
        Peter 0
        """), SpriteKind.player)
    controller.move_sprite(_3s)
    scene.camera_follow_sprite(_3s)
    tiles.place_on_tile(_3s, tiles.get_tile_location(2, 27))

def on_up_pressed():
    global double_jump
    double_jump += 1
    if double_jump < 3:
        mySprite.vy = -200
    animation.run_image_animation(mySprite,
        [img("""
                ........................................
                ........................................
                ..................fff...................
                .................fcccf..................
                .................fccccfff...............
                ................ffcccccccf..............
                ...............fcffeeeffff..............
                ..............ffffff4efff...............
                ..............fffe44f4c.................
                ...............ffe4444..................
                ..................f44...................
                .................fcbdf..................
                ................fff1dfc.................
                ..............ccccfcccff................
                .............fcccccccccccffffff.........
                .............fcccccf5ccccffeeef.........
                ............fccfccc555ccceeefff.........
                ...........ffccfcccb5eccc5eecff.........
                ...........cffffcccc5cccc5fecff.........
                ............ccccffcccccfee444...........
                ...........fcccfffccccccffe4e...........
                ...........ccfcffccccfcffcfff...........
                ...........fcccfffcffffffcffc...........
                ............fffffcfcfccf.fff............
                .............ffffcccccfcf.ff............
                ..............fffcccccfcf...............
                ..............cffcccccfcf...............
                ...............fccccccfcf...............
                ...............fccccccfcf...............
                ...............fccccccfcf...............
                ..............fcccccccfcf...............
                ..............fcccccccfcf...............
                ..............fcccccccfcff..............
                ..............fcccccccfcff..............
                ..............ccccccccfcff..............
                .............cccccccccfcff..............
                .............ffcccccccfcff..............
                .............fccccccccccff..............
                .............fccccccccfcff..............
                .............fcccccccfccff..............
                ............ffcccccccfccfc..............
                ............ffcccccccfccfc..............
                ............ffccccccccccfc..............
                ............ffccccccfcccfc..............
                ............ffccccccfcccfcc.............
                ...........cffccccccfcccffc.............
                ...........ffccccccfccccfff.............
                ...........ffccccfcfccccfff.............
                .............ccccccccffff...............
                ..............fff....fffff..............
                """),
            img("""
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ....................bfffb...............
                ....................fcccf...............
                ....................fccccffff...........
                ...................ffcccccccf...........
                ..................fcffeeeffff...........
                .................ffffff4efff............
                .................fffe44f4c..............
                ..................ffe4444...............
                ..................bdffb3................
                ..4444effccbbbcccfffccddfb.......cc.....
                ...44eefccccfcccccccfccccfcffcfcfcf444..
                .....ffffccccfcccccccfcccccccfcfccf44...
                .....ffffccccffccccccff5cccccfcfccf.....
                .....ffffcccccffcffcce555ccffcfcccf.....
                .....cfffccccccffffcccc5cccfcffcccf.....
                ......fffffffffffffcccc5ccfffffffcf.....
                ......fffff.....cffcccccccf....cfc......
                ................cffcccccccf.............
                ................cffccccccf..............
                .................ffcccfcfc..............
                .................fcfffffff..............
                ................cfcccfcfcfffccbb........
                ................ffcccccffcccccccb.......
                ................fccccccfcccccccccbb.....
                .......bfb1.....fccccccfccccccccccc.....
                .......fffbb....fcccccccccccccccccc.....
                ......fffccffffffccccccccccfcccfffc.....
                .....ffffccfffffccccccccfccffffffb......
                .....fffcccfcffcccccccccccffffffc.......
                ........ccffcfccccccccccffffffff........
                .........cffcfcccccccccfffffffff........
                ..........cfccccccccccfffffffff.........
                ...........ffccccccccfffffffff..........
                ............fcccccccfffffffff...........
                ............fccccccffffff...............
                .............cfccffffcfffb..............
                ..............ffffffc..fff..............
                ........................ff..............
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                """),
            img("""
                ........................................
                ........................................
                ..................fff...................
                .................fcccf..................
                .................fccccfff...............
                ................ffcccccccf..............
                ...............fcffeeeffff..............
                ..............ffffff4efff...............
                ..............fffe44f4c.................
                ...............ffe4444..................
                ..................f44...................
                .................fcbdf..................
                ................fff1dfc.................
                ..............ccccfcccff................
                .............fcccccccccccffffff.........
                .............fcccccf5ccccffeeef.........
                ............fccfccc555ccceeefff.........
                ...........ffccfcccb5eccc5eecff.........
                ...........cffffcccc5cccc5fecff.........
                ............ccccffcccccfee444...........
                ...........fcccfffccccccffe4e...........
                ...........ccfcffccccfcffcfff...........
                ...........fcccfffcffffffcffc...........
                ............fffffcfcfccf.fff............
                .............ffffcccccfcf.ff............
                ..............fffcccccfcf...............
                ..............cffcccccfcf...............
                ...............fccccccfcf...............
                ...............fccccccfcf...............
                ...............fccccccfcf...............
                ..............fcccccccfcf...............
                ..............fcccccccfcf...............
                ..............fcccccccfcff..............
                ..............fcccccccfcff..............
                ..............ccccccccfcff..............
                .............cccccccccfcff..............
                .............ffcccccccfcff..............
                .............fccccccccccff..............
                .............fccccccccfcff..............
                .............fcccccccfccff..............
                ............ffcccccccfccfc..............
                ............ffcccccccfccfc..............
                ............ffccccccccccfc..............
                ............ffccccccfcccfc..............
                ............ffccccccfcccfcc.............
                ...........cffccccccfcccffc.............
                ...........ffccccccfccccfff.............
                ...........ffccccfcfccccfff.............
                .............ccccccccffff...............
                ..............fff....fffff..............
                """)],
        100,
        False)
controller.up.on_event(ControllerButtonEvent.PRESSED, on_up_pressed)

def Riddle():
    game.set_dialog_frame(img("""
        9999999999999999999999999999999999999999999999999999999999..
        9999ffff9999999999999999ffff9999999999999999fff99999999999..
        99fffffffff999fffff999ffffffff9999fffff99fffffffff9999fff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ff2ffffffffffffffffffffffffffffffffffffffffffffff2ffffff9..
        9ff2ffffffffffffffffffffffffffffffffffffffffffffff2ffffff9..
        9ff2ffffffffff2ffffffffffffffffffffffffff22ffffff22ffffff9..
        9ff222ffffffff222ffffffffffffffffffffffff22fffffff2ffff2f9..
        9222ffffffffff2ffffffffffffffffff2fffffff222fffff222fff2f9..
        9222ffffffffff2ffffffffffffffffff2fffffff222fffff222fff2f9..
        982222ff5ffff2222fffff2ffffffffff2ffffff222ffffff22fff22f9..
        9882222f5fffff2fffffff2ffffffff2222ffffff222fff22222fff2f9..
        9222ff555555222222ffff22fffffff222fffffff2222ffff22fff2229..
        9822222f5fff22222fff22222fffff222222fff2222ffff22222ff2289..
        9822222f5fff22222fff22222fffff222222fff2222ffff22222ff2289..
        9822222f5fff22222fffff22fffffff222ffffff2222fff22252222229..
        922222ff5ff2222222ff22222fffff222222fff22222f2222252222229..
        9822fffff22222222fff22222ffff222222ffff2222222255555552229..
        92222222fff22222222222222222222222222222222222222252222229..
        92222222fff22222222222222222222222222222222222222252222229..
        9222222ff2222222222222222222222222222222222222222252222229..
        9222222222222222222222222222222222222222222222222252222229..
        9999999999999999999999999999999999999999999999999999999999..
        """))
    game.set_dialog_text_color(5)
    game.show_long_text("God sent His only begotten Son into the world to save mankind; your coming today is just as your God did on that day.",
        DialogLayout.CENTER)
    level_2()

def on_on_overlap(sprite, otherSprite):
    story.sprite_say_text(village1, "Do you know red is danger,Orange is lucky?", 15)
    story.print_character_text("do you know what I mean?", "Tony")
    story.show_player_choices("Yes", "NO", "Again")
    if story.check_last_answer("Yes"):
        tiles.place_on_tile(_2s, tiles.get_tile_location(24, 48))
    elif story.check_last_answer("No"):
        story.print_character_text("......", "Tony")
    else:
        story.sprite_say_text(village1, "Do you know red is danger,Orange is lucky?", 15)
sprites.on_overlap(SpriteKind.player, SpriteKind.VILl1, on_on_overlap)

def last():
    global last_sprite, Benkey
    last_sprite = sprites.create(assets.image("""
        Peter 1
        """), SpriteKind.player)
    controller.move_sprite(last_sprite)
    scene.camera_follow_sprite(last_sprite)
    tiles.place_on_tile(last_sprite, tiles.get_tile_location(3, 17))
    scene.set_tile_map(assets.image("""
        bushi center
        """))
    scene.set_tile(2, assets.image("""
        bamboo
        """), True)
    scene.set_tile(7, assets.image("""
        wood
        """), True)
    scene.set_tile(5,
        img("""
            6 6 6 6 6 6 6 6 6 6 6 6 6 . . .
            7 7 7 7 7 6 6 6 7 7 7 7 7 6 6 .
            7 7 7 7 7 7 6 7 7 7 7 7 7 7 6 .
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 6
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 6
            7 7 7 7 7 7 7 7 7 7 7 7 7 6 7 6
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 6 8
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 8
            7 6 7 7 7 7 6 7 7 7 7 6 7 7 7 6
            7 7 6 7 7 6 7 7 7 6 7 7 6 6 8 6
            7 7 6 7 6 6 7 7 6 6 6 7 6 6 6 8
            6 7 6 6 6 6 7 6 6 6 6 6 8 6 6 8
            8 8 6 6 8 6 6 6 8 6 6 6 8 8 8 8
            8 e 6 e e 8 6 6 8 8 6 8 8 8 e 8
            8 e e e e e 6 e 8 8 e e 8 e e f
            f e e e e f 8 e e 8 e e e e e f
            """),
        True)
    Benkey = sprites.create(assets.image("""
        bushi
        """), SpriteKind.Boss)
    tiles.place_on_tile(Benkey, tiles.get_tile_location(20, 18))
    Benkey.follow(last_sprite, 30)
    Benkey.ay += 500

def on_a_pressed():
    story.clear_all_text()
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_on_overlap2(sprite2, otherSprite2):
    sprites.destroy(otherSprite2)
    lv2()
sprites.on_overlap(SpriteKind.player, SpriteKind.gateway2, on_on_overlap2)

def _2_tilemap():
    pass
def lv2_element3():
    global gateway3
    gateway3 = sprites.create(assets.image("""
        tomb2
        """), SpriteKind.gate3)
    tiles.place_on_tile(gate, tiles.get_tile_location(29, 28))
def enmies():
    pass

def on_left_pressed():
    animation.run_image_animation(mySprite,
        [img("""
                ........................................
                ........................................
                ...................fff..................
                ..................fcccf.................
                ...............fffccccf.................
                ..............fcccccccff................
                ..............ffffeeeffcf...............
                ...............fffe4ffffff..............
                .................c4f44efff..............
                ..................4444eff...............
                ...................44f..................
                ..................fdbcf.................
                .................cfd1fff................
                ................ffcccfcccc..............
                .........ffffffcccccccccccf.............
                .........feeeffcccc5fcccccf.............
                .........fffeeeccc555cccfccf............
                .........ffcee5ccce5bcccfccff...........
                .........ffcef5cccc5ccccffffc...........
                ...........444eefcccccffcccc............
                ...........e4effccccccfffcccf...........
                ...........fffcffcfccccffcfcc...........
                ...........cffcffffffcfffcccf...........
                ............fff.fccfcfcfffff............
                ............ff.fcfcccccffff.............
                ...............fcfcccccfff..............
                ...............fcfcccccffc..............
                ...............fcfccccccf...............
                ...............fcfccccccf...............
                ...............fcfccccccf...............
                ...............fcfcccccccf..............
                ...............fcfcccccccf..............
                ..............ffcfcccccccf..............
                ..............ffcfcccccccf..............
                ..............ffcfcccccccc..............
                ..............ffcfccccccccc.............
                ..............ffcfcccccccff.............
                ..............ffccccccccccf.............
                ..............ffcfccccccccf.............
                ..............ffccfcccccccf.............
                ..............cfccfcccccccff............
                ..............cfccfcccccccff............
                ..............cfccccccccccff............
                ..............cfcccfccccccff............
                .............ccfcccfccccccff............
                .............cffcccfccccccffc...........
                .............fffccccfccccccff...........
                .............fffccccfcfccccff...........
                ...............ffffcccccccc.............
                ..............fffff....fff..............
                """),
            img("""
                ........................................
                ........................................
                ........................................
                ..................fff...................
                .................fcccf..................
                ..............fffccccf..................
                .............fcccccccffb................
                .............ffffeeeffcf................
                ..............fffe4ffffff...............
                ................c4f44efff...............
                .................4444eff................
                ..................44f...................
                ...............1.fdbcf..................
                ................cfd1fff.................
                ...............ffcccfcccc...............
                ........ffffffcccccccccccf..............
                ........feeefffccc5fcccccf..............
                ........fffeeefcc555cccfccf.............
                ........ffcee5fcce5bcccfcccf............
                ........ffcef5fccc5ccccfccccf...........
                ..........444eefccccccfffccccf..........
                ..........e4effcccccccffffcccf..........
                ..........fffcffcfccccff.fccccf.........
                ..........cffcffffffcffb.ffcccf.........
                ..........cfff.fccfcfcff.ffcccc.........
                ..........bff..cfccccccf..fccccf........
                ...........ff..cfccccccf..ffccf.........
                ...............cffcccccf..fffee.........
                ...............cfccccccf....4444........
                ...............cfccccccf....4e44........
                ...............cfccccccf.....e4.........
                ...............fccccccfff....ee.........
                ...............fccccccccf...............
                ...............fcccccffff...............
                ..............fccccccffff...............
                ..............fcccccffffcf..............
                .............fcccccfffffff..............
                .............fccccfcccfffff.............
                .............fcccccccccffff.............
                .............ccccccfcccccccff...........
                .............ccccccfcccccccff...........
                .............ccccccfcccccccfcc..........
                ............fcccccccfccccffff...........
                ...........ffcccccccfccccffff...........
                ...........fffffffcccfccffffff..........
                ............cfff.ffffffcc..ffff.........
                ............ffff...ffb.....fff..........
                ........ff..fff...........fff...........
                ........fffffff..........fff............
                .........fffff..........................
                """),
            img("""
                ........................................
                ........................................
                ...................fff..................
                ..................fcccf.................
                ...............fffccccf.................
                ..............fcccccccff................
                ..............ffffeeeffcf...............
                ...............fffe4ffffff..............
                .................c4f44efff..............
                ..................4444eff...............
                ...................44f..................
                ..................fdbcf.................
                .................cfd1fff................
                ................ffcccfcccc..............
                .........ffffffcccccccccccf.............
                .........feeeffcccc5fcccccf.............
                .........fffeeeccc555cccfccf............
                .........ffcee5ccce5bcccfccff...........
                .........ffcef5cccc5ccccffffc...........
                ...........444eefcccccffcccc............
                ...........e4effccccccfffcccf...........
                ...........fffcffcfccccffcfcc...........
                ...........cffcffffffcfffcccf...........
                ............fff.fccfcfcfffff............
                ............ff.fcfcccccffff.............
                ...............fcfcccccfff..............
                ...............fcfcccccffc..............
                ...............fcfccccccf...............
                ...............fcfccccccf...............
                ...............fcfccccccf...............
                ...............fcfcccccccf..............
                ...............fcfcccccccf..............
                ..............ffcfcccccccf..............
                ..............ffcfcccccccf..............
                ..............ffcfcccccccc..............
                ..............ffcfccccccccc.............
                ..............ffcfcccccccff.............
                ..............ffccccccccccf.............
                ..............ffcfccccccccf.............
                ..............ffccfcccccccf.............
                ..............cfccfcccccccff............
                ..............cfccfcccccccff............
                ..............cfccccccccccff............
                ..............cfcccfccccccff............
                .............ccfcccfccccccff............
                .............cffcccfccccccffc...........
                .............fffccccfccccccff...........
                .............fffccccfcfccccff...........
                ...............ffffcccccccc.............
                ..............fffff....fff..............
                """)],
        100,
        False)
controller.left.on_event(ControllerButtonEvent.PRESSED, on_left_pressed)

def StatusBars():
    global Kuro_HP, BenkeyHP
    Kuro_HP = statusbars.create(20, 4, StatusBarKind.health)
    BenkeyHP = statusbars.create(20, 4, StatusBarKind.enemy_health)
    BenkeyHP.value = 100
    Kuro_HP.attach_to_sprite(last_sprite, 10, 0)
    BenkeyHP.attach_to_sprite(Benkey, 10, 0)
    Kuro_HP.set_color(7, 2, 3)
    BenkeyHP.set_color(7, 2, 3)
    Kuro_HP.set_label("HP")
    BenkeyHP.set_label("HP")
    Kuro_HP.set_status_bar_flag(StatusBarFlag.SMOOTH_TRANSITION, True)
    BenkeyHP.set_status_bar_flag(StatusBarFlag.SMOOTH_TRANSITION, True)
    BenkeyHP.set_bar_border(1, 13)

def on_on_overlap3(sprite3, otherSprite3):
    sprites.destroy(otherSprite3)
    Riddle()
sprites.on_overlap(SpriteKind.player, SpriteKind.Gateway, on_on_overlap3)

def _1_start():
    scene.set_background_image(assets.image("""
        myImage3
        """))
    music.play(music.create_song(hex("""
            0078000408020401001c000f05001202c102c201000405002800000064002800031400060200040c0010001400011430003400011404001c00100500640000041e000004000000000000000000000000000a0400043c0000000400011d08000c00011e10001400012014001800011e18001c00011d20002400011d28002c00011e30003400012034003800011e38003c00011d07001c00020a006400f401640000040000000000000000000000000000000003180000000400011110001400011120002400011130003400011109010e02026400000403780000040a000301000000640001c80000040100000000640001640000040100000000fa0004af00000401c80000040a00019600000414000501006400140005010000002c0104dc00000401fa0000040a0001c8000004140005d0076400140005d0070000c800029001f40105c201f4010a0005900114001400039001000005c201f4010500058403050032000584030000fa00049001000005c201f4010500058403c80032000584030500640005840300009001049001000005c201f4010500058403c80064000584030500c8000584030000f40105ac0d000404a00f00000a0004ac0d2003010004a00f0000280004ac0d9001010004a00f0000280002d00700040408070f0064000408070000c80003c800c8000e7d00c80019000e64000f0032000e78000000fa00032c01c8000ee100c80019000ec8000f0032000edc000000fa0003f401c8000ea901c80019000e90010f0032000ea4010000fa0001c8000004014b000000c800012c01000401c8000000c8000190010004012c010000c80002c800000404c8000f0064000496000000c80002c2010004045e010f006400042c010000640002c409000404c4096400960004f6090000f40102b80b000404b80b64002c0104f40b0000f401022003000004200300040a000420030000ea01029001000004900100040a000490010000900102d007000410d0076400960010d0070000c8000c001c001d000104200021000104
            """)),
        music.PlaybackMode.LOOPING_IN_BACKGROUND)
    pause(200)
    scene.set_background_image(assets.image("""
        myImage2
        """))
    game.show_long_text("Peter, I need you to go to Japan for an important mission, for years, we keep sending our man to Nagasaki for our glory mission, none of them can come back. I need you travel to Nagasaki to rescue them and the missionary work.",
        DialogLayout.BOTTOM)
    pause(100)
    game.show_long_text("Yes, in the name of god, I'll fulfill the mission as a missionary and rescue them, whatever takes.",
        DialogLayout.TOP)
    pause(100)
    music.stop_all_sounds()
    scene.set_background_image(assets.image("""
        myImage5
        """))
    scene.set_tile_map(assets.image("""
        tin
        """))
    scene.set_tile(14, assets.image("""
        船
        """), False)
    scene.set_tile(5,
        img("""
            d 1 1 1 1 1 1 b d 1 1 1 1 1 1 b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d d 1 d d d d d d d
            b b b b b b d e b b b b b b d e
            d 1 1 1 1 1 1 b d 1 1 1 1 1 1 b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d d 1 d d d d d d d
            b b b b b b d e d b b b b b b e
            """),
        True)
    scene.set_tile(2,
        img("""
            d 1 1 1 1 1 1 b d 1 1 1 1 1 1 b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d d 1 d d d d d d d
            b b b b b b d e b b b b b b d e
            d 1 1 1 1 1 1 b d 1 1 1 1 1 1 b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d b 1 d d d d d d b
            1 d d d d d d d 1 d d d d d d d
            b b b b b b d e d b b b b b b e
            """),
        True)
    scene.set_tile(13,
        img("""
            d 1 d d d d d d d 1 d d d d d d
            d 1 d d d d d d d 1 d d d d d d
            d 1 d d d d d d d 1 d d d d d d
            1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
            d d d d d 1 d d d d d d d 1 d d
            d d d d d 1 d d d d d d d 1 d d
            d d d d d 1 d d d d d d d 1 d d
            1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
            d 1 d d d d d d d 1 d d d d d d
            d 1 d d d d d d d 1 d d d d d d
            d 1 d d d d d d d 1 d d d d d d
            1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
            d d d d d 1 d d d d d d d 1 d d
            d d d d d 1 d d d d d d d 1 d d
            d d d d d 1 d d d d d d d 1 d d
            1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
            """),
        True)
    scene.set_tile(6,
        img("""
            d d d d d d d d d d d d d d d d
            d d d 1 1 d d d d d d d d b d d
            d d d 1 1 d d d d d d d d d d d
            d d d d d d d d d d d d d d d d
            d d b d d d d d d b b d d d d d
            d d d d d d d d d b b d d d d d
            d d d d d d d d d d d d d d d d
            d d d d d d d d d d d d d d d d
            d d d d d b d d d d d d d d d d
            d d d d d d d d d d d d d d d d
            d d d d d d d d d d d d d d d d
            1 1 d d d d d d d d d d d d d d
            1 1 d d d d d d d d d d b d d d
            d d d d d d 1 d d d d d d d d d
            d d d d d d d d d d d d d d d d
            d d d d d d d d d d d d d d b d
            """),
        False)
    scene.set_tile(15,
        img("""
            d 1 1 1 1 1 1 1 1 1 1 1 1 1 1 b
            1 d d d d d d d d d d d d d d b
            1 d d d d d d d d d d d d d d b
            1 d d d d d d d d d d d d d d b
            1 d d d d d d d d d d d d d d b
            1 d d d d d d d d d d d d d d b
            1 d d d d d d d d d d d d d d b
            1 d d d d d d d d d d d d d d b
            1 d d d d d d d d d d d d d d b
            1 d d d d d d d d d d d d d d b
            1 d d d d d d d d d d d d d d b
            1 d d d d d d d d d d d d d d b
            1 d d d d d d d d d d d d d d b
            1 d d d d d d d d d d d d d d b
            1 d d d d d d d d d d d d d d b
            b b b b b b b b b b b b b b b b
            """),
        False)

def on_on_overlap4(sprite4, otherSprite4):
    info.change_score_by(50)
    story.sprite_say_text(village2,
        "Bushi usually place the key in the beautiful golden case",
        15)
    game.show_long_text("welcome to lv2", DialogLayout.BOTTOM)
    _3_sprite_LV2()
sprites.on_overlap(SpriteKind.player, SpriteKind.VIL2, on_on_overlap4)

def on_on_overlap5(sprite5, otherSprite5):
    info.change_score_by(20)
    story.sprite_say_text(sprite5, "some place with torch always have sushi", 15)
sprites.on_overlap(SpriteKind.player, SpriteKind.VIL3, on_on_overlap5)

def lv1_asset():
    global village1, village2, village_3
    village1 = sprites.create(assets.image("""
        village 1
        """), SpriteKind.VILl1)
    tiles.place_on_tile(village1, tiles.get_tile_location(10, 58))
    village2 = sprites.create(assets.image("""
        village3
        """), SpriteKind.VIL2)
    tiles.place_on_tile(village2, tiles.get_tile_location(9, 50))
    village_3 = sprites.create(assets.image("""
        village 3
        """), SpriteKind.VIL3)
    tiles.place_on_tile(village_3, tiles.get_tile_location(41, 50))

def on_hit_tile(sprite6):
    last()
scene.on_hit_tile(SpriteKind.player, 7, on_hit_tile)

def on_on_zero(status):
    
    def on_start_cutscene():
        story.print_character_text("this is not fun I quit", "looeg9")
        story.print_character_text("bye bye drumbass", "Sam")
    story.start_cutscene(on_start_cutscene)
    
    Benkey.destroy(effects.blizzard, 2000)
    last_sprite.destroy(effects.disintegrate, 2000)
    game.set_dialog_frame(img("""
        88888..8888888888888888....88888.
        87768888777877787778777888867778.
        87777686767876767678767688777778.
        87767767667676676676766786776768.
        8677676767767767677677678676778..
        .877768777686767776867678667768..
        .886668888888888888888888886688..
        .888888866666666666666668877768..
        88677786666666666666666668766778.
        87766686666666666666666668776678.
        87667786666666666666666668677778.
        87777686666666666666666668866888.
        88866886666666666666666668677778.
        87777686666666666666666668776678.
        87667786666666666666666668666778.
        87766786666666666666666668777688.
        88677786666666666666666668766778.
        87766686666666666666666668776678.
        87667786666666666666666668677778.
        87777686666666666666666668866888.
        88866886666666666666666668677778.
        87777686666666666666666668776678.
        87667786666666666666666668666778.
        87766786666666666666666668777688.
        .867778866666666666666668888888..
        .886688888888888888888888866688..
        .867766876768677767686777867778..
        .8776768767767767677677676767768.
        86767768766767667667676676776778.
        87777788676787676767876768677778.
        87776888877787778777877788886778.
        88888..88888888888888888....8888.
        .................................
        """))
    game.show_long_text("Congratulation, you save your friend Sammy",
        DialogLayout.TOP)
    game.over(True, effects.splatter)
statusbars.on_zero(StatusBarKind.enemy_health, on_on_zero)

def _3_sprite_LV1():
    global mySprite
    mySprite = sprites.create(assets.image("""
        Peter 1
        """), SpriteKind.player)
    controller.move_sprite(mySprite, 100, 0)
    scene.place_on_random_tile(mySprite, 1)
    scene.camera_follow_sprite(mySprite)
    mySprite.ay = 500

def on_on_zero2(status2):
    game.over(False, effects.blizzard)
statusbars.on_zero(StatusBarKind.health, on_on_zero2)

def on_right_pressed():
    animation.run_image_animation(mySprite,
        [img("""
                ........................................
                ........................................
                ..................fff...................
                .................fcccf..................
                .................fccccfff...............
                ................ffcccccccf..............
                ...............fcffeeeffff..............
                ..............ffffff4efff...............
                ..............fffe44f4c.................
                ...............ffe4444..................
                ..................f44...................
                .................fcbdf..................
                ................fff1dfc.................
                ..............ccccfcccff................
                .............fcccccccccccffffff.........
                .............fcccccf5ccccffeeef.........
                ............fccfccc555ccceeefff.........
                ...........ffccfcccb5eccc5eecff.........
                ...........cffffcccc5cccc5fecff.........
                ............ccccffcccccfee444...........
                ...........fcccfffccccccffe4e...........
                ...........ccfcffccccfcffcfff...........
                ...........fcccfffcffffffcffc...........
                ............fffffcfcfccf.fff............
                .............ffffcccccfcf.ff............
                ..............fffcccccfcf...............
                ..............cffcccccfcf...............
                ...............fccccccfcf...............
                ...............fccccccfcf...............
                ...............fccccccfcf...............
                ..............fcccccccfcf...............
                ..............fcccccccfcf...............
                ..............fcccccccfcff..............
                ..............fcccccccfcff..............
                ..............ccccccccfcff..............
                .............cccccccccfcff..............
                .............ffcccccccfcff..............
                .............fccccccccccff..............
                .............fccccccccfcff..............
                .............fcccccccfccff..............
                ............ffcccccccfccfc..............
                ............ffcccccccfccfc..............
                ............ffccccccccccfc..............
                ............ffccccccfcccfc..............
                ............ffccccccfcccfcc.............
                ...........cffccccccfcccffc.............
                ...........ffccccccfccccfff.............
                ...........ffccccfcfccccfff.............
                .............ccccccccffff...............
                ..............fff....fffff..............
                """),
            img("""
                ........................................
                ........................................
                ........................................
                ...................fff..................
                ..................fcccf.................
                ..................fccccfff..............
                ................bffcccccccf.............
                ................fcffeeeffff.............
                ...............ffffff4efff..............
                ...............fffe44f4c................
                ................ffe4444.................
                ...................f44..................
                ..................fcbdf.1...............
                .................fff1dfc................
                ...............ccccfcccff...............
                ..............fcccccccccccffffff........
                ..............fcccccf5cccfffeeef........
                .............fccfccc555ccfeeefff........
                ............fcccfcccb5eccf5eecff........
                ...........fccccfcccc5cccf5fecff........
                ..........fccccfffccccccfee444..........
                ..........fcccffffcccccccffe4e..........
                .........fccccf.ffccccfcffcfff..........
                .........fcccff.bffcffffffcffc..........
                .........ccccff.ffcfcfccf.fffc..........
                ........fccccf..fccccccfc..ffb..........
                .........fccff..fccccccfc..ff...........
                .........eefff..fcccccffc...............
                ........4444....fccccccfc...............
                ........44e4....fccccccfc...............
                .........4e.....fccccccfc...............
                .........ee....fffccccccf...............
                ...............fccccccccf...............
                ...............ffffcccccf...............
                ...............ffffccccccf..............
                ..............fcffffcccccf..............
                ..............fffffffcccccf.............
                .............fffffcccfccccf.............
                .............ffffcccccccccf.............
                ...........ffcccccccfcccccc.............
                ...........ffcccccccfcccccc.............
                ..........ccfcccccccfcccccc.............
                ...........ffffccccfcccccccf............
                ...........ffffccccfcccccccff...........
                ..........ffffffccfcccfffffff...........
                .........ffff..ccffffff.fffc............
                ..........fff.....bff...ffff............
                ...........fff...........fff..ff........
                ............fff..........fffffff........
                ..........................fffff.........
                """),
            img("""
                ........................................
                ........................................
                ..................fff...................
                .................fcccf..................
                .................fccccfff...............
                ................ffcccccccf..............
                ...............fcffeeeffff..............
                ..............ffffff4efff...............
                ..............fffe44f4c.................
                ...............ffe4444..................
                ..................f44...................
                .................fcbdf..................
                ................fff1dfc.................
                ..............ccccfcccff................
                .............fcccccccccccffffff.........
                .............fcccccf5ccccffeeef.........
                ............fccfccc555ccceeefff.........
                ...........ffccfcccb5eccc5eecff.........
                ...........cffffcccc5cccc5fecff.........
                ............ccccffcccccfee444...........
                ...........fcccfffccccccffe4e...........
                ...........ccfcffccccfcffcfff...........
                ...........fcccfffcffffffcffc...........
                ............fffffcfcfccf.fff............
                .............ffffcccccfcf.ff............
                ..............fffcccccfcf...............
                ..............cffcccccfcf...............
                ...............fccccccfcf...............
                ...............fccccccfcf...............
                ...............fccccccfcf...............
                ..............fcccccccfcf...............
                ..............fcccccccfcf...............
                ..............fcccccccfcff..............
                ..............fcccccccfcff..............
                ..............ccccccccfcff..............
                .............cccccccccfcff..............
                .............ffcccccccfcff..............
                .............fccccccccccff..............
                .............fccccccccfcff..............
                .............fcccccccfccff..............
                ............ffcccccccfccfc..............
                ............ffcccccccfccfc..............
                ............ffccccccccccfc..............
                ............ffccccccfcccfc..............
                ............ffccccccfcccfcc.............
                ...........cffccccccfcccffc.............
                ...........ffccccccfccccfff.............
                ...........ffccccfcfccccfff.............
                .............ccccccccffff...............
                ..............fff....fffff..............
                """)],
        100,
        False)
controller.right.on_event(ControllerButtonEvent.PRESSED, on_right_pressed)

def on_on_overlap6(sprite7, otherSprite6):
    Kuro_HP.value += -3
sprites.on_overlap(SpriteKind.player, SpriteKind.projectile, on_on_overlap6)

def lv3():
    game.set_dialog_text_color(2)
    game.set_dialog_cursor(img("""
        9999999999999999999999999999999999999999999999999999999999..
        9999ffff9999999999999999ffff9999999999999999fff99999999999..
        99fffffffff999fffff999ffffffff9999fffff99fffffffff9999fff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9..
        9ff2ffffffffffffffffffffffffffffffffffffffffffffff2ffffff9..
        9ff2ffffffffffffffffffffffffffffffffffffffffffffff2ffffff9..
        9ff2ffffffffff2ffffffffffffffffffffffffff22ffffff22ffffff9..
        9ff222ffffffff222ffffffffffffffffffffffff22fffffff2ffff2f9..
        9222ffffffffff2ffffffffffffffffff2fffffff222fffff222fff2f9..
        9222ffffffffff2ffffffffffffffffff2fffffff222fffff222fff2f9..
        982222ff5ffff2222fffff2ffffffffff2ffffff222ffffff22fff22f9..
        9882222f5fffff2fffffff2ffffffff2222ffffff222fff22222fff2f9..
        9222ff555555222222ffff22fffffff222fffffff2222ffff22fff2229..
        9822222f5fff22222fff22222fffff222222fff2222ffff22222ff2289..
        9822222f5fff22222fff22222fffff222222fff2222ffff22222ff2289..
        9822222f5fff22222fffff22fffffff222ffffff2222fff22252222229..
        922222ff5ff2222222ff22222fffff222222fff22222f2222252222229..
        9822fffff22222222fff22222ffff222222ffff2222222255555552229..
        92222222fff22222222222222222222222222222222222222252222229..
        92222222fff22222222222222222222222222222222222222252222229..
        9222222ff2222222222222222222222222222222222222222252222229..
        9222222222222222222222222222222222222222222222222252222229..
        9999999999999999999999999999999999999999999999999999999999..
        """))
    game.show_long_text("Finally we get into the house, let me preach the leader of sushi",
        DialogLayout.CENTER)
def lv2_element2():
    global gate2
    gate2 = sprites.create(assets.image("""
        tomb2
        """), SpriteKind.gateway2)
    tiles.place_on_tile(gate, tiles.get_tile_location(13, 50))
def level_2():
    sprites.destroy_all_sprites_of_kind(SpriteKind.player, effects.spray, 500)
    sprites.destroy_all_sprites_of_kind(SpriteKind.enemy, effects.spray, 500)
    sprites.destroy_all_sprites_of_kind(SpriteKind.projectile, effects.spray, 500)
    sprites.destroy_all_sprites_of_kind(SpriteKind.Gateway, effects.spray, 500)
    scene.set_background_image(assets.image("""
        myImage
        """))
    scene.set_tile_map(assets.image("""
        mushroom village
        """))
    scene.set_tile(13,
        img("""
            d d d d d d d d d d d d d d d d
            d d d 1 1 d d d d d d d d b d d
            d d d 1 1 d d d d d d d d d d d
            d d d d d d d d d d d d d d d d
            d d b d d d d d d b b d d d d d
            d d d d d d d d d b b d d d d d
            d d d d d d d d d d d d d d d d
            d d d d d d d d d d d d d d d d
            d d d d d b d d d d d d d d d d
            d d d d d d d d d d d d d d d d
            d d d d d d d d d d d d d d d d
            1 1 d d d d d d d d d d d d d d
            1 1 d d d d d d d d d d b d d d
            d d d d d d 1 d d d d d d d d d
            d d d d d d d d d d d d d d d d
            d d d d d d d d d d d d d d b d
            """),
        True)
    scene.set_tile(10,
        img("""
            d 1 d d d d d d d 1 d d d d d d
            d 1 d d d d d d d 1 d d d d d d
            d 1 d d d d d d d 1 d d d d d d
            1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
            d d d d d 1 d d d d d d d 1 d d
            d d d d d 1 d d d d d d d 1 d d
            d d d d d 1 d d d d d d d 1 d d
            1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
            d 1 d d d d d d d 1 d d d d d d
            d 1 d d d d d d d 1 d d d d d d
            d 1 d d d d d d d 1 d d d d d d
            1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
            d d d d d 1 d d d d d d d 1 d d
            d d d d d 1 d d d d d d d 1 d d
            d d d d d 1 d d d d d d d 1 d d
            1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
            """),
        True)
    scene.set_tile(1, assets.image("""
        start
        """), False)
    scene.set_tile(5,
        img("""
            6 6 6 6 6 6 6 6 6 6 6 6 6 . . .
            7 7 7 7 7 6 6 6 7 7 7 7 7 6 6 .
            7 7 7 7 7 7 6 7 7 7 7 7 7 7 6 .
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 6
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 6
            7 7 7 7 7 7 7 7 7 7 7 7 7 6 7 6
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 6 8
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 8
            7 6 7 7 7 7 6 7 7 7 7 6 7 7 7 6
            7 7 6 7 7 6 7 7 7 6 7 7 6 6 8 6
            7 7 6 7 6 6 7 7 6 6 6 7 6 6 6 8
            6 7 6 6 6 6 7 6 6 6 6 6 8 6 6 8
            8 8 6 6 8 6 6 6 8 6 6 6 8 8 8 8
            8 e 6 e e 8 6 6 8 8 6 8 8 8 e 8
            8 e e e e e 6 e 8 8 e e 8 e e f
            f e e e e f 8 e e 8 e e e e e f
            """),
        True)
    lv2_sprite()
    story.print_character_text("To leave this place, I must go to the port. At least try to save anyone on the road, in the name of god. There are many house on the road, I need key to unlock them.",
        "Peter")
    game.show_long_text("welcome to stage 2", DialogLayout.BOTTOM)
def lv2():
    pass

def on_on_overlap7(sprite8, otherSprite7):
    lv3()
sprites.on_overlap(SpriteKind.player, SpriteKind.gate3, on_on_overlap7)

def lv2_sprite():
    global _2s
    _2s = sprites.create(assets.image("""
        Peter 1
        """), SpriteKind.player)
    controller.move_sprite(_2s, 100, 0)
    scene.camera_follow_sprite(_2s)
    _2s.ay = 500
    scene.place_on_random_tile(_2s, 1)
def lv1_element():
    global gate
    gate = sprites.create(assets.image("""
        tomb2
        """), SpriteKind.Gateway)
    tiles.place_on_tile(gate, tiles.get_tile_location(8, 27))

def on_on_overlap8(sprite9, otherSprite8):
    sprites.destroy(otherSprite8, effects.halo, 1000)
sprites.on_overlap(SpriteKind.player, SpriteKind.enemy, on_on_overlap8)

def on_on_overlap9(sprite10, otherSprite9):
    last_sprite.vx = -200
    if last_sprite.x < Benkey.x:
        last_sprite.x += -30
    elif last_sprite.x > Benkey.x:
        last_sprite.x += 30
    Kuro_HP.value += -20
    BenkeyHP.value += 20
sprites.on_overlap(SpriteKind.player, SpriteKind.Boss, on_on_overlap9)

mySprite3: Sprite = None
BenkeySpear: Sprite = None
mySprite2: Sprite = None
gate2: Sprite = None
village_3: Sprite = None
village2: Sprite = None
BenkeyHP: StatusBarSprite = None
Kuro_HP: StatusBarSprite = None
gate: Sprite = None
gateway3: Sprite = None
Benkey: Sprite = None
last_sprite: Sprite = None
_2s: Sprite = None
village1: Sprite = None
mySprite: Sprite = None
_3s: Sprite = None
double_jump = 0
info.set_score(0)
double_jump = 0
_1_start()
_2_tilemap()
_3_sprite_LV1()
lv1_element()
lv1_asset()

def on_on_update():
    global double_jump
    if mySprite.is_hitting_tile(CollisionDirection.BOTTOM):
        double_jump = 0
game.on_update(on_on_update)

def on_update_interval():
    global mySprite2
    mySprite2 = sprites.create(assets.image("""
        typhoon
        """), SpriteKind.enemy)
    tiles.place_on_random_tile(mySprite2, assets.tile("""
        RED
        """))
    mySprite2.follow(mySprite, 10)
game.on_update_interval(5000, on_update_interval)

def on_update_interval2():
    global BenkeySpear
    if last_sprite.x < Benkey.x:
        BenkeySpear = sprites.create_projectile_from_sprite(assets.image("""
            lingnan bomb
            """), Benkey, -80, 0)
        BenkeySpear.set_kind(SpriteKind.Spear)
        BenkeySpear.y += randint(-20, 20)
    elif last_sprite.x > Benkey.x:
        BenkeySpear = sprites.create_projectile_from_sprite(assets.image("""
            light attack2
            """), Benkey, 80, 0)
        BenkeySpear.set_kind(SpriteKind.Spear)
        BenkeySpear.y += randint(-20, 20)
game.on_update_interval(1000, on_update_interval2)

def on_update_interval3():
    global mySprite3
    mySprite3 = sprites.create(assets.image("""
        enmi
        """), SpriteKind.Ghost)
    scene.place_on_random_tile(mySprite3, 9)
    mySprite3.set_velocity(-20, 10)
    mySprite3.set_bounce_on_wall(True)
game.on_update_interval(10000, on_update_interval3)
