namespace SpriteKind {
    export const w = SpriteKind.create()
    export const key = SpriteKind.create()
    export const box = SpriteKind.create()
    export const cookie = SpriteKind.create()
    export const Gateway = SpriteKind.create()
    export const map = SpriteKind.create()
    export const IN = SpriteKind.create()
    export const VILl1 = SpriteKind.create()
    export const gateway2 = SpriteKind.create()
    export const KEYD = SpriteKind.create()
    export const VIL2 = SpriteKind.create()
    export const VIL3 = SpriteKind.create()
    export const gate3 = SpriteKind.create()
    export const Ghost = SpriteKind.create()
    export const Boss = SpriteKind.create()
    export const Spear = SpriteKind.create()
    export const VIL4 = SpriteKind.create()
    export const score_paper = SpriteKind.create()
    export const wizer123 = SpriteKind.create()
    export const Peter_attack = SpriteKind.create()
    export const wiser_attack = SpriteKind.create()
    export const apple = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.KEYD, function (sprite, otherSprite) {
    for (let value7 of tiles.getTilesByType(assets.tile`myTile17`)) {
        music.play(music.melodyPlayable(music.baDing), music.PlaybackMode.UntilDone)
        tiles.setWallAt(value7, false)
        tiles.setTileAt(value7, assets.tile`myTile16`)
    }
})
sprites.onOverlap(SpriteKind.Ghost, SpriteKind.Player, function (sprite, otherSprite) {
    sprites.destroy(sprite, effects.halo, 500)
    info.changeScoreBy(-1)
    info.changeLifeBy(-1)
})
function LV25_Element () {
    for (let value4 of tiles.getTilesByType(assets.tile`myTile13`)) {
        tiles.setTileAt(value4, assets.tile`wood`)
    }
    for (let value5 of tiles.getTilesByType(assets.tile`myTile12`)) {
        tiles.setTileAt(value5, assets.tile`myTile12`)
    }
    for (let value_11 of tiles.getTilesByType(assets.tile`Paper`)) {
        paper = sprites.create(assets.image`paper`, SpriteKind.score_paper)
        tiles.placeOnTile(paper, value_11)
        tiles.setTileAt(value_11, assets.tile`transparency16`)
    }
    gate25 = sprites.create(assets.image`tomb0`, SpriteKind.gateway2)
    tiles.placeOnTile(gate25, tiles.getTileLocation(35, 14))
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Level == 1) {
        double_jump += 1
        if (double_jump < 3) {
            Peter_1.vy = -200
        }
        animation.runImageAnimation(
        Peter_1,
        [img`
            ........................................
            ........................................
            ..................fff...................
            .................fcccf..................
            .................fccccfff...............
            ................ffcccccccf..............
            ...............fcffeeeffff..............
            ..............ffffff4efff...............
            ..............fffe44f4c.................
            ...............ffe4444..................
            ..................f44...................
            .................fcbdf..................
            ................fff1dfc.................
            ..............ccccfcccff................
            .............fcccccccccccffffff.........
            .............fcccccf5ccccffeeef.........
            ............fccfccc555ccceeefff.........
            ...........ffccfcccb5eccc5eecff.........
            ...........cffffcccc5cccc5fecff.........
            ............ccccffcccccfee444...........
            ...........fcccfffccccccffe4e...........
            ...........ccfcffccccfcffcfff...........
            ...........fcccfffcffffffcffc...........
            ............fffffcfcfccf.fff............
            .............ffffcccccfcf.ff............
            ..............fffcccccfcf...............
            ..............cffcccccfcf...............
            ...............fccccccfcf...............
            ...............fccccccfcf...............
            ...............fccccccfcf...............
            ..............fcccccccfcf...............
            ..............fcccccccfcf...............
            ..............fcccccccfcff..............
            ..............fcccccccfcff..............
            ..............ccccccccfcff..............
            .............cccccccccfcff..............
            .............ffcccccccfcff..............
            .............fccccccccccff..............
            .............fccccccccfcff..............
            .............fcccccccfccff..............
            ............ffcccccccfccfc..............
            ............ffcccccccfccfc..............
            ............ffccccccccccfc..............
            ............ffccccccfcccfc..............
            ............ffccccccfcccfcc.............
            ...........cffccccccfcccffc.............
            ...........ffccccccfccccfff.............
            ...........ffccccfcfccccfff.............
            .............ccccccccffff...............
            ..............fff....fffff..............
            `,img`
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ....................bfffb...............
            ....................fcccf...............
            ....................fccccffff...........
            ...................ffcccccccf...........
            ..................fcffeeeffff...........
            .................ffffff4efff............
            .................fffe44f4c..............
            ..................ffe4444...............
            ..................bdffb3................
            ..4444effccbbbcccfffccddfb.......cc.....
            ...44eefccccfcccccccfccccfcffcfcfcf444..
            .....ffffccccfcccccccfcccccccfcfccf44...
            .....ffffccccffccccccff5cccccfcfccf.....
            .....ffffcccccffcffcce555ccffcfcccf.....
            .....cfffccccccffffcccc5cccfcffcccf.....
            ......fffffffffffffcccc5ccfffffffcf.....
            ......fffff.....cffcccccccf....cfc......
            ................cffcccccccf.............
            ................cffccccccf..............
            .................ffcccfcfc..............
            .................fcfffffff..............
            ................cfcccfcfcfffccbb........
            ................ffcccccffcccccccb.......
            ................fccccccfcccccccccbb.....
            .......bfb1.....fccccccfccccccccccc.....
            .......fffbb....fcccccccccccccccccc.....
            ......fffccffffffccccccccccfcccfffc.....
            .....ffffccfffffccccccccfccffffffb......
            .....fffcccfcffcccccccccccffffffc.......
            ........ccffcfccccccccccffffffff........
            .........cffcfcccccccccfffffffff........
            ..........cfccccccccccfffffffff.........
            ...........ffccccccccfffffffff..........
            ............fcccccccfffffffff...........
            ............fccccccffffff...............
            .............cfccffffcfffb..............
            ..............ffffffc..fff..............
            ........................ff..............
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            `,img`
            ........................................
            ........................................
            ..................fff...................
            .................fcccf..................
            .................fccccfff...............
            ................ffcccccccf..............
            ...............fcffeeeffff..............
            ..............ffffff4efff...............
            ..............fffe44f4c.................
            ...............ffe4444..................
            ..................f44...................
            .................fcbdf..................
            ................fff1dfc.................
            ..............ccccfcccff................
            .............fcccccccccccffffff.........
            .............fcccccf5ccccffeeef.........
            ............fccfccc555ccceeefff.........
            ...........ffccfcccb5eccc5eecff.........
            ...........cffffcccc5cccc5fecff.........
            ............ccccffcccccfee444...........
            ...........fcccfffccccccffe4e...........
            ...........ccfcffccccfcffcfff...........
            ...........fcccfffcffffffcffc...........
            ............fffffcfcfccf.fff............
            .............ffffcccccfcf.ff............
            ..............fffcccccfcf...............
            ..............cffcccccfcf...............
            ...............fccccccfcf...............
            ...............fccccccfcf...............
            ...............fccccccfcf...............
            ..............fcccccccfcf...............
            ..............fcccccccfcf...............
            ..............fcccccccfcff..............
            ..............fcccccccfcff..............
            ..............ccccccccfcff..............
            .............cccccccccfcff..............
            .............ffcccccccfcff..............
            .............fccccccccccff..............
            .............fccccccccfcff..............
            .............fcccccccfccff..............
            ............ffcccccccfccfc..............
            ............ffcccccccfccfc..............
            ............ffccccccccccfc..............
            ............ffccccccfcccfc..............
            ............ffccccccfcccfcc.............
            ...........cffccccccfcccffc.............
            ...........ffccccccfccccfff.............
            ...........ffccccfcfccccfff.............
            .............ccccccccffff...............
            ..............fff....fffff..............
            `],
        500,
        false
        )
    }
    if (Level == 4) {
        double_jump += 1
        if (double_jump < 3) {
            peter4.vy = -200
        }
        animation.runImageAnimation(
        peter4,
        [img`
            ........................................
            ........................................
            ..................fff...................
            .................fcccf..................
            .................fccccfff...............
            ................ffcccccccf..............
            ...............fcffeeeffff..............
            ..............ffffff4efff...............
            ..............fffe44f4c.................
            ...............ffe4444..................
            ..................f44...................
            .................fcbdf..................
            ................fff1dfc.................
            ..............ccccfcccff................
            .............fcccccccccccffffff.........
            .............fcccccf5ccccffeeef.........
            ............fccfccc555ccceeefff.........
            ...........ffccfcccb5eccc5eecff.........
            ...........cffffcccc5cccc5fecff.........
            ............ccccffcccccfee444...........
            ...........fcccfffccccccffe4e...........
            ...........ccfcffccccfcffcfff...........
            ...........fcccfffcffffffcffc...........
            ............fffffcfcfccf.fff............
            .............ffffcccccfcf.ff............
            ..............fffcccccfcf...............
            ..............cffcccccfcf...............
            ...............fccccccfcf...............
            ...............fccccccfcf...............
            ...............fccccccfcf...............
            ..............fcccccccfcf...............
            ..............fcccccccfcf...............
            ..............fcccccccfcff..............
            ..............fcccccccfcff..............
            ..............ccccccccfcff..............
            .............cccccccccfcff..............
            .............ffcccccccfcff..............
            .............fccccccccccff..............
            .............fccccccccfcff..............
            .............fcccccccfccff..............
            ............ffcccccccfccfc..............
            ............ffcccccccfccfc..............
            ............ffccccccccccfc..............
            ............ffccccccfcccfc..............
            ............ffccccccfcccfcc.............
            ...........cffccccccfcccffc.............
            ...........ffccccccfccccfff.............
            ...........ffccccfcfccccfff.............
            .............ccccccccffff...............
            ..............fff....fffff..............
            `,img`
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ....................bfffb...............
            ....................fcccf...............
            ....................fccccffff...........
            ...................ffcccccccf...........
            ..................fcffeeeffff...........
            .................ffffff4efff............
            .................fffe44f4c..............
            ..................ffe4444...............
            ..................bdffb3................
            ..4444effccbbbcccfffccddfb.......cc.....
            ...44eefccccfcccccccfccccfcffcfcfcf444..
            .....ffffccccfcccccccfcccccccfcfccf44...
            .....ffffccccffccccccff5cccccfcfccf.....
            .....ffffcccccffcffcce555ccffcfcccf.....
            .....cfffccccccffffcccc5cccfcffcccf.....
            ......fffffffffffffcccc5ccfffffffcf.....
            ......fffff.....cffcccccccf....cfc......
            ................cffcccccccf.............
            ................cffccccccf..............
            .................ffcccfcfc..............
            .................fcfffffff..............
            ................cfcccfcfcfffccbb........
            ................ffcccccffcccccccb.......
            ................fccccccfcccccccccbb.....
            .......bfb1.....fccccccfccccccccccc.....
            .......fffbb....fcccccccccccccccccc.....
            ......fffccffffffccccccccccfcccfffc.....
            .....ffffccfffffccccccccfccffffffb......
            .....fffcccfcffcccccccccccffffffc.......
            ........ccffcfccccccccccffffffff........
            .........cffcfcccccccccfffffffff........
            ..........cfccccccccccfffffffff.........
            ...........ffccccccccfffffffff..........
            ............fcccccccfffffffff...........
            ............fccccccffffff...............
            .............cfccffffcfffb..............
            ..............ffffffc..fff..............
            ........................ff..............
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            `,img`
            ........................................
            ........................................
            ..................fff...................
            .................fcccf..................
            .................fccccfff...............
            ................ffcccccccf..............
            ...............fcffeeeffff..............
            ..............ffffff4efff...............
            ..............fffe44f4c.................
            ...............ffe4444..................
            ..................f44...................
            .................fcbdf..................
            ................fff1dfc.................
            ..............ccccfcccff................
            .............fcccccccccccffffff.........
            .............fcccccf5ccccffeeef.........
            ............fccfccc555ccceeefff.........
            ...........ffccfcccb5eccc5eecff.........
            ...........cffffcccc5cccc5fecff.........
            ............ccccffcccccfee444...........
            ...........fcccfffccccccffe4e...........
            ...........ccfcffccccfcffcfff...........
            ...........fcccfffcffffffcffc...........
            ............fffffcfcfccf.fff............
            .............ffffcccccfcf.ff............
            ..............fffcccccfcf...............
            ..............cffcccccfcf...............
            ...............fccccccfcf...............
            ...............fccccccfcf...............
            ...............fccccccfcf...............
            ..............fcccccccfcf...............
            ..............fcccccccfcf...............
            ..............fcccccccfcff..............
            ..............fcccccccfcff..............
            ..............ccccccccfcff..............
            .............cccccccccfcff..............
            .............ffcccccccfcff..............
            .............fccccccccccff..............
            .............fccccccccfcff..............
            .............fcccccccfccff..............
            ............ffcccccccfccfc..............
            ............ffcccccccfccfc..............
            ............ffccccccccccfc..............
            ............ffccccccfcccfc..............
            ............ffccccccfcccfcc.............
            ...........cffccccccfcccffc.............
            ...........ffccccccfccccfff.............
            ...........ffccccfcfccccfff.............
            .............ccccccccffff...............
            ..............fff....fffff..............
            `],
        500,
        false
        )
    }
})
function Lv25 () {
    sprites.destroy(Peter_1)
    sprites.destroyAllSpritesOfKind(SpriteKind.gateway2)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    sprites.destroyAllSpritesOfKind(SpriteKind.Food)
    Peter2 = sprites.create(assets.image`Peter 1`, SpriteKind.Player)
    tiles.placeOnTile(Peter2, tiles.getTileLocation(4, 13))
    controller.moveSprite(Peter2, 100, 0)
    scene.cameraFollowSprite(Peter2)
    LV25_Mushroom_V()
    LV25_Element()
    lv25_villager()
}
function Lv2_riddle () {
    music.stopAllSounds()
    game.showLongText("There are two way to go, Should i go to mushroom village or find the key of bushi. home? ", DialogLayout.Bottom)
    story.printCharacterText("How could i choose?", "Peter")
    story.showPlayerChoices("Mushroom village", "maze")
    if (story.checkLastAnswer("Mushroom village")) {
        Lv25()
    } else if (story.checkLastAnswer("maze")) {
        LV2()
    }
}
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    music.play(music.melodyPlayable(music.magicWand), music.PlaybackMode.InBackground)
    timer.throttle("action", 200, function () {
        if (info.score() >= 1) {
            if (Level == 4) {
                if (peter4.x < Benkey.x) {
                    projectile = sprites.createProjectileFromSprite(assets.image`bibie`, peter4, 80, 0)
                    info.changeScoreBy(-1)
                } else if (peter4.x > Benkey.x) {
                    projectile = sprites.createProjectileFromSprite(assets.image`bibie`, peter4, -80, 0)
                    info.changeScoreBy(-1)
                }
                projectile.setKind(SpriteKind.Peter_attack)
            }
        }
    })
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.VILl1, function (sprite, otherSprite) {
    story.spriteSayText(otherSprite, "Green always safe", 15)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.VIL4, function (sprite, otherSprite) {
    story.spriteSayText(otherSprite, "bushi tend to put the key on the golden pressure box", 15)
})
function BOSSStatusBars () {
    Kuro_HP = statusbars.create(20, 4, StatusBarKind.Health)
    BenkeyHP = statusbars.create(20, 4, StatusBarKind.EnemyHealth)
    BenkeyHP.value = 100
    Kuro_HP.attachToSprite(peter4, 10, 0)
    BenkeyHP.attachToSprite(Benkey, 10, 0)
    Kuro_HP.setColor(7, 2, 3)
    BenkeyHP.setColor(7, 2, 3)
    Kuro_HP.setLabel("HP")
    BenkeyHP.setLabel("HP")
    Kuro_HP.setStatusBarFlag(StatusBarFlag.SmoothTransition, true)
    BenkeyHP.setStatusBarFlag(StatusBarFlag.SmoothTransition, true)
    BenkeyHP.setBarBorder(1, 13)
    if (Kuro_HP.value < 50) {
        color.startFade(color.originalPalette, color.GrayScale, 5000)
    }
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    story.clearAllText()
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.score_paper, function (sprite, otherSprite) {
    sprites.destroy(otherSprite, effects.spray, 500)
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.gateway2, function (sprite, otherSprite) {
    sprites.destroy(Peter2)
    sprites.destroyAllSpritesOfKind(SpriteKind.VILl1)
    sprites.destroyAllSpritesOfKind(SpriteKind.VIL2)
    sprites.destroyAllSpritesOfKind(SpriteKind.VIL4)
    sprites.destroyAllSpritesOfKind(SpriteKind.VIL3)
    sprites.destroyAllSpritesOfKind(SpriteKind.Food)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    sprites.destroyAllSpritesOfKind(SpriteKind.Player)
    LV2()
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Level == 1) {
        animation.runImageAnimation(
        Peter_1,
        assets.animation`left`,
        500,
        false
        )
    }
    if (Level == 4) {
        animation.runImageAnimation(
        peter4,
        assets.animation`left`,
        500,
        false
        )
    }
})
function Lv1_element () {
    for (let value1 of tiles.getTilesByType(assets.tile`船版`)) {
        tiles.setTileAt(value1, assets.tile`船版`)
    }
    for (let value2 of tiles.getTilesByType(assets.tile`Fish`)) {
        fish = sprites.create(assets.image`fish`, SpriteKind.Food)
        tiles.placeOnTile(fish, value2)
        tiles.setTileAt(value2, assets.tile`transparency16`)
        animation.runMovementAnimation(
        fish,
        animation.animationPresets(animation.shake),
        2000,
        true
        )
    }
    for (let value3 of tiles.getTilesByType(assets.tile`myTile8`)) {
        tiles.setTileAt(value3, assets.tile`myTile12`)
    }
    for (let value_11 of tiles.getTilesByType(assets.tile`Paper`)) {
        paper = sprites.create(assets.image`paper`, SpriteKind.score_paper)
        tiles.placeOnTile(paper, value_11)
        tiles.setTileAt(value_11, assets.tile`transparency16`)
    }
    for (let value_12 of tiles.getTilesByType(assets.tile`sea11`)) {
        sea = sprites.create(assets.image`sea`, SpriteKind.Enemy)
        tiles.placeOnTile(sea, value_12)
        tiles.setTileAt(value_12, assets.tile`transparency16`)
    }
    gate1 = sprites.create(assets.image`tomb2`, SpriteKind.Gateway)
    tiles.placeOnTile(gate1, tiles.getTileLocation(115, 13))
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Gateway, function (sprite, otherSprite) {
    LV12()
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.VIL2, function (sprite, otherSprite) {
    story.spriteSayText(otherSprite, "Reading the Bible can strengthen us.", 15)
})
function opening () {
    scene.setBackgroundImage(assets.image`Cover pages`)
    pause(2000)
    music.play(music.createSong(hex`0078000408020500001c00010a006400f401640000040000000000000000000000000005000004240000000400011d08000c00011e10001400012014001800011e18001c00011d20002400011d01001c000f05001202c102c201000405002800000064002800031400060200040c0010001400011430003400011404001c00100500640000041e000004000000000000000000000000000a0400043c0000000400011d08000c00011e10001400012014001800011e18001c00011d20002400011d28002c00011e30003400012034003800011e38003c00011d07001c00020a006400f401640000040000000000000000000000000000000003180000000400011110001400011120002400011130003400011109010e02026400000403780000040a000301000000640001c80000040100000000640001640000040100000000fa0004af00000401c80000040a00019600000414000501006400140005010000002c0104dc00000401fa0000040a0001c8000004140005d0076400140005d0070000c800029001f40105c201f4010a0005900114001400039001000005c201f4010500058403050032000584030000fa00049001000005c201f4010500058403c80032000584030500640005840300009001049001000005c201f4010500058403c80064000584030500c8000584030000f40105ac0d000404a00f00000a0004ac0d2003010004a00f0000280004ac0d9001010004a00f0000280002d00700040408070f0064000408070000c80003c800c8000e7d00c80019000e64000f0032000e78000000fa00032c01c8000ee100c80019000ec8000f0032000edc000000fa0003f401c8000ea901c80019000e90010f0032000ea4010000fa0001c8000004014b000000c800012c01000401c8000000c8000190010004012c010000c80002c800000404c8000f0064000496000000c80002c2010004045e010f006400042c010000640002c409000404c4096400960004f6090000f40102b80b000404b80b64002c0104f40b0000f401022003000004200300040a000420030000ea01029001000004900100040a000490010000900102d007000410d0076400960010d0070000c8000c001c001d000104200021000104`), music.PlaybackMode.LoopingInBackground)
    music.setVolume(50)
    pause(200)
    scene.setBackgroundImage(assets.image`myImage2`)
    game.showLongText("Peter, I need you to go to Japan for an important mission, for years, we keep sending our man to Nagasaki for our glory mission, none of them can come back. I need you travel to Nagasaki to rescue them and the missionary work.", DialogLayout.Bottom)
    pause(100)
    game.showLongText("Yes, in the name of god, I'll fulfill the mission as a missionary and rescue them, whatever takes.", DialogLayout.Bottom)
    music.stopAllSounds()
    scene.setBackgroundImage(assets.image`myImage6`)
    music.play(music.createSong(assets.song`japan sea`), music.PlaybackMode.LoopingInBackground)
    Level += 1
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.VIL3, function (sprite, otherSprite) {
    story.spriteSayText(otherSprite, "Pastor Leo is our guide; you must save him.", 15)
})
info.onCountdownEnd(function () {
    game.showLongText("You were discovered by samurai on your way to the bamboo forest and were seriously injured. bible -10", DialogLayout.Bottom)
    info.changeScoreBy(-10)
})
sprites.onOverlap(SpriteKind.wiser_attack, SpriteKind.Player, function (sprite, otherSprite) {
    sprites.destroy(sprite, effects.fire, 500)
    Kuro_HP.value += -5
})
function LV12 () {
    game.setDialogFrame(assets.image`op`)
    game.setDialogTextColor(5)
    game.showLongText("God sent His only begotten Son into the world to save mankind; your coming today is just as your God did on that day.", DialogLayout.Center)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    sprites.destroyAllSpritesOfKind(SpriteKind.KEYD)
    sprites.destroyAllSpritesOfKind(SpriteKind.score_paper)
    Lv2_riddle()
}
statusbars.onZero(StatusBarKind.EnemyHealth, function (status) {
    music.play(music.createSong(assets.song`Via Sactus`), music.PlaybackMode.LoopingInBackground)
    story.startCutscene(function () {
        story.printCharacterText("How dare you……., you", "shogun")
        story.printCharacterText("Shut up, I abandoned, but it doesn’t mean I’ll listen to you", "Peter")
    })
    Benkey.destroy(effects.blizzard, 2000)
    peter4.destroy(effects.disintegrate, 2000)
    game.setDialogFrame(assets.image`op`)
    game.showLongText("Congratulation, you save your friend Leo,", DialogLayout.Top)
    game.showLongText("But your faith journey is still long and continues until your Lord returns.", DialogLayout.Bottom)
    game.setDialogFrame(assets.image`op`)
    game.over(true, effects.splatter)
})
function LV2 () {
    sprites.destroy(Peter2)
    sprites.destroyAllSpritesOfKind(SpriteKind.VILl1)
    sprites.destroyAllSpritesOfKind(SpriteKind.VIL2)
    sprites.destroyAllSpritesOfKind(SpriteKind.VIL4)
    sprites.destroyAllSpritesOfKind(SpriteKind.VIL3)
    sprites.destroyAllSpritesOfKind(SpriteKind.Food)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    sprites.destroyAllSpritesOfKind(SpriteKind.Player)
    Peter3 = sprites.create(assets.image`Peter 0`, SpriteKind.Player)
    controller.moveSprite(Peter3, 150, 150)
    tiles.placeOnTile(Peter3, tiles.getTileLocation(0, 9))
    scene.cameraFollowSprite(Peter3)
    lv2_tilemap()
    Lv2_Element()
    music.play(music.createSong(assets.song`mysterious`), music.PlaybackMode.LoopingInBackground)
}
statusbars.onZero(StatusBarKind.Health, function (status) {
    story.printCharacterText("Foreign devil, give up! Your gods are trash.", "shogun")
    story.printCharacterText("Although my body has collapsed, the Lord will comfort me. All glory to God.", "Peter")
    music.play(music.createSong(assets.song`shadow of edo`), music.PlaybackMode.LoopingInBackground)
    game.over(false, effects.blizzard)
    game.gameOver(false)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Level == 1) {
        animation.runImageAnimation(
        Peter_1,
        assets.animation`right`,
        500,
        false
        )
    }
    if (Level == 4) {
        animation.runImageAnimation(
        peter4,
        assets.animation`left`,
        500,
        false
        )
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.apple, function (sprite, otherSprite) {
    sprites.destroy(otherSprite, effects.spray, 500)
    info.changeScoreBy(4)
    Kuro_HP.value += 5
})
function Lv3_tilemap () {
    game.setDialogTextColor(2)
    game.setDialogFrame(assets.image`op`)
    game.showLongText("Finally we get into the house, let me preach the leader of sushi", DialogLayout.Full)
    music.stopAllSounds()
    info.stopCountdown()
    sprites.destroy(Peter3)
    sprites.destroyAllSpritesOfKind(SpriteKind.gate3)
    sprites.destroyAllSpritesOfKind(SpriteKind.Gateway)
    sprites.destroyAllSpritesOfKind(SpriteKind.Ghost)
    sprites.destroyAllSpritesOfKind(SpriteKind.gateway2)
    scene.setBackgroundImage(assets.image`frighing`)
    tiles.setCurrentTilemap(tilemap`level6`)
    story.printCharacterText("Shogun, stop this meaningless fight, listen to the god, accept our god. Release those missionaries please", "Peter")
    story.printCharacterText("Die or abandon your religion, this is Japan, we don’t believe what you said and your god. One last chance, follow my order, or die with those missionaries.", "shogun")
    Level = 4
    peter4 = sprites.create(assets.image`Peter 1`, SpriteKind.Player)
    controller.moveSprite(peter4, 100, 0)
    Benkey = sprites.create(assets.image`bushi`, SpriteKind.Boss)
    peter4.ay = 500
    scene.cameraFollowSprite(peter4)
    tiles.placeOnTile(peter4, tiles.getTileLocation(6, 27))
    tiles.placeOnTile(Benkey, tiles.getTileLocation(34, 27))
    Benkey.follow(peter4, 30)
    Benkey.ay += 500
    wizer = sprites.create(assets.image`wizer12`, SpriteKind.wizer123)
    tiles.placeOnRandomTile(wizer, assets.tile`尖刺`)
    gunman = sprites.create(assets.image`iron`, SpriteKind.wizer123)
    tiles.placeOnRandomTile(gunman, assets.tile`myTile22`)
    for (let apple123 of tiles.getTilesByType(assets.tile`apple`)) {
        apple1 = sprites.create(assets.image`Newton apple`, SpriteKind.apple)
        tiles.placeOnTile(apple1, apple123)
        tiles.setTileAt(apple123, assets.tile`myTile14`)
    }
    BOSSStatusBars()
    music.play(music.createSong(assets.song`bamboo forest bgm`), music.PlaybackMode.LoopingInBackground)
}
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    sprites.destroy(sprite, effects.spray, 500)
    info.changeLifeBy(-1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.gate3, function (sprite, otherSprite) {
    sprites.destroy(Peter3)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    sprites.destroyAllSpritesOfKind(SpriteKind.gate3)
    Lv3_tilemap()
})
info.onLifeZero(function () {
    game.showLongText("You collapsed while searching for your friend. Go back to Macau.", DialogLayout.Center)
    game.setGameOverEffect(false, effects.melt)
    game.gameOver(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    sprites.destroy(otherSprite, effects.spray, 500)
    info.changeLifeBy(1)
})
function Lv2_Element () {
    sprites.destroy(typhoon)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    for (let value_6 of tiles.getTilesByType(assets.tile`key2`)) {
        KEY1 = sprites.create(assets.tile`real chest`, SpriteKind.KEYD)
        tiles.setTileAt(value_6, assets.tile`real chest`)
        tiles.placeOnTile(KEY1, tiles.getTileLocation(10, 10))
    }
    for (let index = 0; index < 4; index++) {
        for (let value10 of tiles.getTilesByType(assets.tile`ruri`)) {
            RuRI = sprites.create(assets.image`enmi`, SpriteKind.Ghost)
            RuRI.setVelocity(50, 50)
            RuRI.setBounceOnWall(true)
            tiles.placeOnRandomTile(RuRI, assets.tile`ruri`)
            tiles.setTileAt(value10, assets.tile`myTile16`)
        }
    }
    for (let value2 of tiles.getTilesByType(assets.tile`Fish`)) {
        fish = sprites.create(assets.image`fish`, SpriteKind.Food)
        tiles.placeOnTile(fish, value2)
        tiles.setTileAt(value2, assets.tile`myTile16`)
        animation.runMovementAnimation(
        fish,
        animation.animationPresets(animation.shake),
        2000,
        true
        )
    }
    Gate321 = sprites.create(assets.image`tomb0`, SpriteKind.gate3)
    tiles.placeOnTile(Gate321, tiles.getTileLocation(15, 13))
    info.startCountdown(60)
}
function lv1_tilemap () {
    tiles.setCurrentTilemap(tilemap`level0`)
}
function lv25_villager () {
    Villager1 = sprites.create(assets.image`village 1`, SpriteKind.VILl1)
    tiles.placeOnTile(Villager1, tiles.getTileLocation(3, 14))
    Villager2 = sprites.create(assets.image`village 2`, SpriteKind.VIL2)
    tiles.placeOnTile(Villager2, tiles.getTileLocation(11, 14))
    Villager3 = sprites.create(assets.image`village 3`, SpriteKind.VIL3)
    tiles.placeOnTile(Villager3, tiles.getTileLocation(15, 14))
    Villager4 = sprites.create(assets.image`village3`, SpriteKind.VIL4)
    tiles.placeOnTile(Villager4, tiles.getTileLocation(20, 14))
}
sprites.onOverlap(SpriteKind.Peter_attack, SpriteKind.Boss, function (sprite, otherSprite) {
    sprites.destroy(sprite, effects.fire, 200)
    BenkeyHP.value += -10
})
function LV25_Mushroom_V () {
    scene.setBackgroundImage(assets.image`myImage4`)
    tiles.setCurrentTilemap(tilemap`Mushroom V`)
}
sprites.onOverlap(SpriteKind.Spear, SpriteKind.Player, function (sprite, otherSprite) {
    sprites.destroy(sprite, effects.fire, 200)
    Kuro_HP.value += -5
})
function lv2_tilemap () {
    sprites.destroy(Peter2)
    for (let typhoon of sprites.allOfKind(SpriteKind.Enemy)) {
        sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    }
    tiles.setCurrentTilemap(tilemap`level4`)
}
function lv1_sprite () {
    Peter_1 = sprites.create(assets.image`Peter 1`, SpriteKind.Player)
    controller.moveSprite(Peter_1, 100, 0)
    Peter_1.ay = 500
    scene.cameraFollowSprite(Peter_1)
    tiles.placeOnTile(Peter_1, tiles.getTileLocation(1, 15))
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Boss, function (sprite, otherSprite) {
    peter4.vx = -200
    if (peter4.x < Benkey.x) {
        peter4.x += -30
    } else if (peter4.x > Benkey.x) {
        peter4.x += 30
    }
    Kuro_HP.value += -20
    BenkeyHP.value += 20
})
let BenkeySpear: Sprite = null
let projectile2: Sprite = null
let Villager4: Sprite = null
let Villager3: Sprite = null
let Villager2: Sprite = null
let Villager1: Sprite = null
let Gate321: Sprite = null
let RuRI: Sprite = null
let KEY1: Sprite = null
let typhoon: Sprite = null
let apple1: Sprite = null
let gunman: Sprite = null
let wizer: Sprite = null
let Peter3: Sprite = null
let gate1: Sprite = null
let sea: Sprite = null
let fish: Sprite = null
let BenkeyHP: StatusBarSprite = null
let Kuro_HP: StatusBarSprite = null
let projectile: Sprite = null
let Benkey: Sprite = null
let Peter2: Sprite = null
let peter4: Sprite = null
let Peter_1: Sprite = null
let gate25: Sprite = null
let paper: Sprite = null
let Level = 0
let double_jump = 0
double_jump = 0
Level = 0
info.setScore(5)
info.setLife(3)
opening()
lv1_sprite()
lv1_tilemap()
Lv1_element()
game.onUpdate(function () {
    if (Level == 1) {
        if (Peter_1.isHittingTile(CollisionDirection.Bottom)) {
            double_jump = 0
        }
    }
    if (Level == 4) {
        if (peter4.isHittingTile(CollisionDirection.Bottom)) {
            double_jump = 0
        }
    }
})
game.onUpdateInterval(5000, function () {
    if (Level == 4) {
        tiles.placeOnRandomTile(apple1, assets.tile`apple`)
    }
})
game.onUpdateInterval(2000, function () {
    if (Level == 1) {
        typhoon = sprites.create(assets.image`typhoon`, SpriteKind.Enemy)
        tiles.placeOnRandomTile(typhoon, assets.tile`myTile9`)
        typhoon.follow(Peter_1, 50)
    }
})
game.onUpdateInterval(1000, function () {
    if (Level == 4) {
        if (peter4.x < wizer.x) {
            projectile2 = sprites.createProjectileFromSprite(assets.image`bubble`, wizer, -50, 50)
        } else if (peter4.x > wizer.x) {
            projectile2 = sprites.createProjectileFromSprite(assets.image`bubble`, wizer, 50, 50)
        }
        projectile2.setKind(SpriteKind.wiser_attack)
    }
})
game.onUpdateInterval(1000, function () {
    if (Level == 4) {
        if (peter4.x < Benkey.x) {
            BenkeySpear = sprites.createProjectileFromSprite(assets.image`lingnan bomb`, Benkey, -80, 0)
            BenkeySpear.setKind(SpriteKind.Spear)
            BenkeySpear.y += randint(-20, 20)
        } else if (peter4.x > Benkey.x) {
            BenkeySpear = sprites.createProjectileFromSprite(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . 3 b b d d d d d . . 
                . . . . 3 4 b d d . d . d . . . 
                . . . 4 1 b b . d d d d . . . . 
                . . 3 1 b b d d b d . . . . . . 
                . . 4 d 1 9 b d . . . . . . . . 
                . d 5 1 6 6 9 . . . . . . . . . 
                . d 1 9 b 9 d . . . . . . . . . 
                . . 5 9 6 6 b d . . . . . . . . 
                . . 4 1 9 b b d . . . . . . . . 
                . . . 4 9 b b b . . . . . . . . 
                . . . . 4 6 d 9 . . . . . . . . 
                . . . . . 4 d b d d . . . . . . 
                . . . . . . d 4 b b d . . . . . 
                . . . . . . . . . . d . . . . . 
                . . . . . . . . . . . . . . . . 
                `, Benkey, 80, 0)
            BenkeySpear.setKind(SpriteKind.Spear)
            BenkeySpear.y += randint(-20, 20)
        }
    }
})
